cmake_minimum_required(VERSION 3.20)
project(vv_exe CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_GENERATOR_PLATFORM x64)
set(IMGUI_DIR "${CMAKE_SOURCE_DIR}/vendor/imgui")
set(MINHOOK_DIR "${CMAKE_SOURCE_DIR}/vendor/minhook")
include_directories(${CMAKE_SOURCE_DIR}/src ${IMGUI_DIR} ${IMGUI_DIR}/backends ${MINHOOK_DIR}/include ${CMAKE_SOURCE_DIR}/vendor/json/include)
file(GLOB_RECURSE SOURCES "${CMAKE_SOURCE_DIR}/src/*.cpp" "${IMGUI_DIR}/*.cpp" "${IMGUI_DIR}/backends/imgui_impl_opengl3.cpp" "${IMGUI_DIR}/backends/imgui_impl_win32.cpp" "${MINHOOK_DIR}/src/*.c")
add_library(vv_exe SHARED ${SOURCES})
target_link_libraries(vv_exe opengl32 gdi32 user32 jvm.lib)
set_target_properties(vv_exe PROPERTIES PREFIX "" SUFFIX ".dll" OUTPUT_NAME "vv")