cmake_minimum_required(VERSION 3.10)
project(VV_EXE)
set(CMAKE_CXX_STANDARD 17)
file(GLOB_RECURSE SOURCES "src/*.cpp" "src/*.h")
include_directories("src" "src/core" "src/gui" "src/features" "src/math" "src/bypass" "src/config")
add_library(VV_EXE SHARED ${SOURCES})
target_link_libraries(VV_EXE opengl32 d3d11 dxgi psapi)
