#!/usr/bin/env python3
# COPYRIGHT VV.EXE Development Team 2026. All rights reserved.
# IL2CPP Offset Dumper - automatic offset extraction from game

import os
import sys
import re
import subprocess
import random
from pathlib import Path

def find_game_directory():
    # Search for game directory
    possible_paths = [
        r"C:\Games\STALZONE",
        r"C:\Program Files\STALZONE",
        r"C:\Program Files (x86)\STALZONE",
        os.path.expanduser("~\\STALZONE")
    ]
    
    for path in possible_paths:
        if os.path.exists(path):
            game_assembly = os.path.join(path, "GameAssembly.dll")
            metadata = os.path.join(path, "Data", "il2cpp_data", "Metadata", "global-metadata.dat")
            
            if os.path.exists(game_assembly) and os.path.exists(metadata):
                return path, game_assembly, metadata
    
    return None, None, None

def run_il2cpp_dumper(game_assembly, metadata, output_dir):
    # Run Il2CppDumper
    dumper_path = "tools\\Il2CppDumper.exe"
    
    if not os.path.exists(dumper_path):
        print(f"[DUMP] ERROR: Il2CppDumper.exe not found at {dumper_path}")
        print("[DUMP] Please download Il2CppDumper from https://github.com/Perfare/Il2CppDumper")
        return False
    
    print(f"[DUMP] Running Il2CppDumper...")
    print(f"  GameAssembly: {game_assembly}")
    print(f"  Metadata: {metadata}")
    print(f"  Output: {output_dir}")
    
    try:
        result = subprocess.run([dumper_path, game_assembly, metadata, output_dir], 
                              capture_output=True, text=True, timeout=60)
        
        if result.returncode == 0:
            print("[DUMP] Il2CppDumper completed successfully!")
            return True
        else:
            print(f"[DUMP] Il2CppDumper failed with code {result.returncode}")
            print(result.stderr)
            return False
    except subprocess.TimeoutExpired:
        print("[DUMP] Il2CppDumper timeout!")
        return False
    except Exception as e:
        print(f"[DUMP] Error running Il2CppDumper: {e}")
        return False

def parse_dump_cs(dump_cs_path):
    # Parse dump.cs and extract offsets
    offsets = {}
    
    if not os.path.exists(dump_cs_path):
        print(f"[DUMP] ERROR: dump.cs not found at {dump_cs_path}")
        return offsets
    
    print(f"[DUMP] Parsing {dump_cs_path}...")
    
    with open(dump_cs_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find patterns like:
    # public int Health; // 0x100
    # private float _speed; // 0x150
    
    pattern = r'(?:public|private|protected)\s+(?:static\s+)?(?:readonly\s+)?(?:\w+)\s+(\w+)\s*;\s*//\s*(0x[0-9A-Fa-f]+)'
    matches = re.findall(pattern, content)
    
    for name, offset in matches:
        # Convert name to UPPER_CASE
        upper_name = re.sub(r'([A-Z])', r'_\1', name).upper().lstrip('_')
        offsets[upper_name] = offset
    
    print(f"[DUMP] Found {len(offsets)} offsets")
    return offsets

def generate_offsets_header(offsets, output_path):
    # Generate offsets.h with obfuscation
    print(f"[DUMP] Generating {output_path}...")
    
    key = random.randint(1, 255)
    
    lines = [
        "// COPYRIGHT VV.EXE Development Team 2026. All rights reserved.",
        "// Auto-generated by dump_offsets.py",
        "// DO NOT EDIT MANUALLY",
        "#pragma once",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace VV {",
        "namespace Offsets {",
        "",
        "template<size_t N, unsigned char Key>",
        "struct XORDecryptor {",
        "    static constexpr std::array<char, N> decrypt(const unsigned char* data) {",
        "        std::array<char, N> result{};",
        "        for (size_t i = 0; i < N; ++i) {",
        "            result[i] = static_cast<char>(data[i] ^ Key);",
        "        }",
        "        return result;",
        "    }",
        "};",
        "",
        f"// XOR key: 0x{key:02X}",
        ""
    ]
    
    for name, offset in sorted(offsets.items()):
        # Encrypt offset
        encrypted = [ord(c) ^ key for c in offset]
        array_name = f"g_{name}_encrypted"
        
        lines.append(f"constexpr unsigned char {array_name}[] = {{")
        for i in range(0, len(encrypted), 16):
            chunk = encrypted[i:i+16]
            hex_str = ", ".join([f"0x{b:02X}" for b in chunk])
            if i + 16 < len(encrypted):
                lines.append(f"    {hex_str},")
            else:
                lines.append(f"    {hex_str}")
        lines.append("};")
        lines.append(f"constexpr size_t {name}_len = {len(encrypted)};")
        lines.append(f"constexpr uint64_t {name} = []() {{")
        lines.append(f"    constexpr auto decrypted = XORDecryptor<{len(encrypted)}, 0x{key:02X}>::decrypt({array_name});")
        lines.append(f"    uint64_t result = 0;")
        lines.append(f"    for (size_t i = 0; i < {len(encrypted)}; ++i) {{")
        lines.append(f"        if (decrypted[i] == 'x') continue;")
        lines.append(f"        result <<= 4;")
        lines.append(f"        char c = decrypted[i];")
        lines.append(f"        if (c >= '0' && c <= '9') result |= (c - '0');")
        lines.append(f"        else if (c >= 'a' && c <= 'f') result |= (c - 'a' + 10);")
        lines.append(f"        else if (c >= 'A' && c <= 'F') result |= (c - 'A' + 10);")
        lines.append(f"    }}")
        lines.append(f"    return result;")
        lines.append(f"}}();")
        lines.append("")
    
    lines.append("} // namespace Offsets")
    lines.append("} // namespace VV")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
    
    print(f"[DUMP] Generated {output_path}")

def main():
    print("====================================")
    print("  VV.EXE IL2CPP Offset Dumper")
    print("  COPYRIGHT VV.EXE Development Team 2026")
    print("====================================")
    print()
    
    # Find game directory
    game_dir, game_assembly, metadata = find_game_directory()
    
    if not game_dir:
        print("[DUMP] ERROR: Game directory not found!")
        print("[DUMP] Please install the game or update the paths in this script.")
        sys.exit(1)
    
    print(f"[DUMP] Game directory: {game_dir}")
    print(f"[DUMP] GameAssembly: {game_assembly}")
    print(f"[DUMP] Metadata: {metadata}")
    print()
    
    # Create temporary output directory
    output_dir = "tools\\dump_output"
    os.makedirs(output_dir, exist_ok=True)
    
    # Run Il2CppDumper
    if not run_il2cpp_dumper(game_assembly, metadata, output_dir):
        sys.exit(1)
    
    # Parse dump.cs
    dump_cs = os.path.join(output_dir, "dump.cs")
    offsets = parse_dump_cs(dump_cs)
    
    if not offsets:
        print("[DUMP] ERROR: No offsets found!")
        sys.exit(1)
    
    # Generate offsets.h
    output_path = "src\\core\\offsets.h"
    generate_offsets_header(offsets, output_path)
    
    print()
    print("====================================")
    print("  Dump completed successfully!")
    print("====================================")
    print(f"  Offsets extracted: {len(offsets)}")
    print(f"  Output file: {output_path}")
    print()

if __name__ == "__main__":
    main()
