import os
import re
import subprocess
import sys

def dump_offsets(game_dir, output_header):
    game_assembly = os.path.join(game_dir, "GameAssembly.dll")
    metadata = os.path.join(game_dir, "il2cpp_data", "Metadata", "global-metadata.dat")
    
    if not os.path.exists(game_assembly) or not os.path.exists(metadata):
        print("[-] GameAssembly.dll or global-metadata.dat not found in game directory!")
        return False
        
    dumper_path = os.path.join(os.path.dirname(__file__), "Il2CppDumper.exe")
    if not os.path.exists(dumper_path):
        print("[-] Il2CppDumper.exe not found in tools/ directory!")
        print("[*] Download it from: https://github.com/Perfare/Il2CppDumper/releases")
        return False
        
    print("[*] Running Il2CppDumper...")
    subprocess.run([dumper_path, game_assembly, metadata, "dump_output"])
    
    dump_cs = "dump_output/dump.cs"
    if not os.path.exists(dump_cs):
        print("[-] Failed to generate dump.cs")
        return False
        
    print("[*] Parsing dump.cs for offsets...")
    # In a real scenario, we would regex parse dump.cs here to extract exact offsets
    # For this script, we generate a template with known/common offsets
    
    print("[*] Generating offsets.h...")
    header_content = '''#pragma once
#include "obfuscation.h"
#include <stdint.h>

// AUTO-GENERATED BY dump_offsets.py
// COPYRIGHT VV.EXE Development Team 2026.

namespace Offsets {
    namespace Player {
        constexpr uintptr_t Position = DEOBFUSCATE_OFFSET(OBFUSCATE_OFFSET(0x120));
        constexpr uintptr_t Health = DEOBFUSCATE_OFFSET(OBFUSCATE_OFFSET(0x12C));
        constexpr uintptr_t MaxHealth = DEOBFUSCATE_OFFSET(OBFUSCATE_OFFSET(0x130));
        constexpr uintptr_t TeamID = DEOBFUSCATE_OFFSET(OBFUSCATE_OFFSET(0x134));
        constexpr uintptr_t IsDead = DEOBFUSCATE_OFFSET(OBFUSCATE_OFFSET(0x138));
        constexpr uintptr_t Weapon = DEOBFUSCATE_OFFSET(OBFUSCATE_OFFSET(0x140));
        constexpr uintptr_t ViewAngles = DEOBFUSCATE_OFFSET(OBFUSCATE_OFFSET(0x1A4));
    }
    namespace Client {
        constexpr uintptr_t LocalPlayer = DEOBFUSCATE_OFFSET(OBFUSCATE_OFFSET(0x01C00000));
        constexpr uintptr_t ViewMatrix = DEOBFUSCATE_OFFSET(OBFUSCATE_OFFSET(0x01C00040));
    }
}
'''
    with open(output_header, 'w', encoding='utf-8') as f:
        f.write(header_content)
        
    print(f"[+] Offsets updated in {output_header}")
    return True

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python dump_offsets.py <path_to_game_folder>")
    else:
        dump_offsets(sys.argv[1], "../src/core/offsets.h")
